language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
    - ~/.npm
  except:
    - /^v\d+\.\d+\.\d+$/
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - npm i -g npm@^6.4.1
  - printf "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
install:
  - npm i
script:
  - npm run build && npm run test:prod
